### ISSUE TITLE
Recreate site using svelte and modern technologies

### ISSUE THREAD

**Issue by hiteacheryouare** [PorkyProductions/porkyproductions.github.io#63]
This site is reaching its limits in terms of scalability. Our plan is to completely change it to use a modern JAM stack framework, such as svelte. We also plan to keep the 100% custom CSS nature of the site.

**Comment by hiteacheryouare** [comment]
TODO: create backup branch right before merge because @HedgehogDubz  has outgoing changes that might mess it up

**Comment by HedgehogDubz** [comment]
I love github merge conflicts

**Comment by hiteacheryouare** [comment]
> I love github merge conflicts

ME TOO!!!
